### ISSUE TITLE
Error in rule split_fasta_lineages

### ISSUE THREAD

**Issue by vinayrajput0005** [rvalieris/LCS#12]
[error.log](https://github.com/rvalieris/LCS/files/10031150/error.log)
Getting error while split_fasta_lineages.
Script is not able to separate the linage data from GISAID full data.

**Traceback (most recent call last):
  File "/data/Student_Data/Vinay/LCS-master/scripts/**split_fasta_by_lineages2**.py", line 52, in <module>
    fn,lineage = l.rstrip().split(",")
ValueError: not enough values to unpack (expected 2, got 1)**

**Comment by vinayrajput0005** [comment]
Pango lineage file is correct 
Lineages.csv (https://github.com/cov-lineages/pango-designation/blob/master/lineages.csv)

**Comment by rvalieris** [comment]
hello,
this error implies the file have a line without any commas, can you run this command on the file and report back the results ?
```
grep -v , data/pango_designation/lineages.csv -m10
```

**Comment by vinayrajput0005** [comment]
(base) test@Workstation2:/data/Student_Data/Vinay/LCS-master/data/pango_designation$ grep -v , lineages.csv 
<<<<<<< HEAD
=======
>>>>>>> master

**Comment by vinayrajput0005** [comment]
bhdnbg

(base) test@NCIM-Workstation2:/data/Student_Data/Vinay/LCS-master/data/pango_designation$ grep -v , lineages.csv 
<<<<<<< HEAD
=======
>>>>>>> master


....

**Comment by vinayrajput0005** [comment]
[Error1.txt](https://github.com/rvalieris/LCS/files/10037757/Error1.txt)

**Comment by vinayrajput0005** [comment]
I removed PANGO_DESIGNATIONS_VERSION='v1.16' from shell command of script.
Now it is downloading the latest lineages.csv file from the git repository.
v.1.16 have some issue with the lineage file
