### ISSUE TITLE
Problem with tags file

### ISSUE THREAD

**Issue by aharring83** [rvalieris/LCS#3]
I made a folder "tags_pool_make" and put a file with my samples names in that folder called make.
When I execute pipeline, I get the following errors:
snakemake --config markers=pango dataset=make --cores 44 --resources mem_gb=100

Building DAG of jobs...
InputFunctionException in line 54 of /data2/harrington/covid/LCS/rules/pools-pipe.py:
Error:
  Exception: tags file not found: data/tags_pool_make
Wildcards:
  z=make
Traceback:
  File "/data2/harrington/covid/LCS/rules/pools-pipe.py", line 55, in <lambda>
  File "/data2/harrington/covid/LCS/rules/config.py", line 40, in get_tags
  File "/data2/harrington/covid/LCS/rules/config.py", line 36, in get_tags_file

**Comment by rvalieris** [comment]
hello,

> Exception: tags file not found: data/tags_pool_make

you need to create the file `data/tags_pool_make` with the sample names, not a folder.

**Comment by aharring83** [comment]
Thank you, it works!
