### ISSUE TITLE
Update provided Pango/UCSC marker tables including Omicron

### ISSUE THREAD

**Issue by hoelzer** [rvalieris/LCS#7]
Could you update our provided tables to also include Omicron? I think this is mainly what people are currently looking for. Thanks!

**Comment by rvalieris** [comment]
for sure !, I just added them to the repo: https://github.com/rvalieris/LCS/commit/4fd9bf2d976cfe9e1ba7ffe0e9b50d46945c91ef

**Comment by hoelzer** [comment]
awesome! thanks!
