### ISSUE TITLE
Paired-end Illumina data

### ISSUE THREAD

**Issue by hoelzer** [rvalieris/LCS#8]
Is it possible to also use the pipeline w/ paired-end data? Thanks!

**Comment by rvalieris** [comment]
it should just work, I'm using paired-end data as well, it should look like this:

```
$ ls data/fastq/
sample1_1.fastq.gz
sample1_2.fastq.gz
sample2_1.fastq.gz
sample2_2.fastq.gz
[....]
```

**Comment by hoelzer** [comment]
He @rvalieris thanks! But then, the paired-end reads are not mapped and analyzed together but separately, or? Or can I write in the `tags_pool_mypool` file something like:

```
sc2-mix
```

when I have in `data/fastq`

```
sc2-mix.R1.fastq.gz
sc2-mix.R2.fastq.gz
```

?

**Comment by hoelzer** [comment]
Ah, I see here 

https://github.com/rvalieris/LCS/blob/master/rules/pools-pipe.py#L13

that the files must be likely named like you already mentioned, so in my case

```
sc2-mix_1.fastq.gz
sc2-mix_2.fastq.gz
```

and then in the `tags_pool_mypool`:

```
sc2-mix
```

I guess

**Comment by rvalieris** [comment]
thats correct ! the filename pattern is important for the pipeline to pick it the pairs.
